#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

DIR=${SCRIPTPATH%/*/*} 
printf "$DIR"

if [[ -d "$DIR/Alib" ]] 
then
	rm -vrf $DIR/Alib/
fi

if [[ -d "$DIR/Blib" ]] 
then
	rm -vrf $DIR/Blib/
fi

if [[ -d "$DIR/build" ]] 
then
	rm -vrf $DIR/build/
fi
